### PR TITLE
Remove old license from C source file

### PR DESCRIPTION
**Pull request by larrybradley**
JD Smith agreed to license the C code as 3-clause BSD, which is reflected in the [LICENSE.rst](https://github.com/spacetelescope/pypolyclip/blob/main/LICENSE.rst) file.

### CODE REVIEW

**Review by Russell-Ryan — COMMENTED** [review]
I don't know the normal policies and procedures.  But modifying the C-file seemed beyond what I understood we were doing.  I know it's just changing the license, but we never cleared that exactly with JD.  Did you talk to him separately?

**Comment by larrybradley** [comment]
No, I just happened to notice the C file had the GNU license in a comment, but that conflicts with the information in the package license file.  I thought JD agreed to the the 3-clause BSD license?

**Comment by Russell-Ryan** [comment]
He did.  I just never confirmed that we’d alter the C file, and I thought it said “ do not alter this file” or something to that effect.  I see your point in that it contains redundant (and in this case, contradictory) information.  We just agreed to use the difference license, which seems like it’d be fine.  I don’t know why he’d agree to the new licensing but not agree to updating the license in the C-file.

Could/Should we put the new license in the old one’s place in the C file?  I dunno.  I’m not objecting, just trying to be above board and grotesquely clear on what we agreed upon. I think it’s fine, as it’s in the spirit of the agreement.  I just wasn’t sure if you told him that we’d modify the license in the C-code.


On Sep 19, 2023, at 10:29 PM, Larry Bradley ***@***.******@***.***>> wrote:



No, I just happened to notice the C file had the GNU license in a comment, but that conflicts with the information in the package license file. I thought JD agreed to the the 3-clause BSD license?

**Review by sosey — CHANGES_REQUESTED** [review]
Looks good larry - except I do not see the BSD 3-clause license statement in the LICENSE file, can you add "BSD 3-Clause License" at the top there to be explicit that everything is under BSD-3?

**Comment by larrybradley** [comment]
@sosey The standard BSD 3-clause license doesn't explicitly say "BSD 3-clause":
https://opensource.org/license/bsd-3-clause/

But added "BSD 3-clause" in the section titles.

**Review by sosey — APPROVED** [review]
thanks!

**Pull request merged**
